version: '3.8'

services:
 web:
  build:
   context: .
  ports:
  - 5000:5000
  volumes:
  - ./:/app

 mysqldb:
  image: mysql
  ports:
  - 3307:3306
  environment:
  - MYSQL_ROOT_PASSWORD=mysqlpassword
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql
 phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql:
    external: true
  mysql_config:
    external: true