
version: '3'
 
services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      # MYSQL_DATABASE: app_db
      # MYSQL_USER: db_user
      # MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  mysql_volume:
   external: true
     
