version: '3.3'

services:
   wordpress:  
    container_name: wordpress
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
    networks:
      - mysql-network
   db:
     container_name: mysql
     image: mysql:8.3.0
     volumes:
       - mysql-volume:/var/lib/mysql
     restart: unless-stopped     
     environment:
      MYSQL_ROOT_PASSWORD: secret  
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      #MYSQL_RANDOM_ROOT_PASSWORD: '1'    
     command: '--default-authentication-plugin=mysql_native_password'

     networks:
      - mysql-network 

   phpmyadmin:
      container_name: phpmyadmin
      depends_on:
       - db
      image: phpmyadmin     
      restart: unless-stopped
      ports:
       - '9002:80'
      environment:
        PMA_HOST: db
      networks:
      - mysql-network
  
volumes:
  wordpress:
   external: true     
  mysql-volume:
   external: true  
networks:
  mysql-network:
    external: true      
    driver: bridge