version: '3'

services:
  # Database
  db:
    image: mysql:8.3.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-volume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: school
      MYSQL_USER: edangol
      MYSQL_PASSWORD: mysqlpassword
    ports:
    - "3306:3306"
    networks:
      - mysql-network
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '9001:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret 
       - PMA_ARBITRARY=1
    networks:
      - mysql-network

  #adminer
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 9002:8080
    networks:
      - mysql-network
networks:
  mysql-network:
   external: true
     
volumes:
  mysql-volume:
   external: true