version: '3'

services:
  # Database
  db:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: school
      MYSQL_USER: edangol
      MYSQL_PASSWORD: mysqlpassword
    ports:
    - "3306:3306"
    networks:
      - mysqlnetwork
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '9001:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mysqlpassword 
       - PMA_ARBITRARY=1
    networks:
      - mysqlnetwork

  #adminer
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 9002:8080
    networks:
      - mysqlnetwork
networks:
  mysqlnetwork:
volumes:
  db_data: