version: '3.8'

services:
  web:
    image: asp8:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: YourPassword123!
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - mssql-volume:/var/opt/mssql

volumes:
  mssql-volume:
   external: true
     
