version: '3.4'

services:
  sql-server:
    container_name: mssql2019
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
    
    ports:
      - 1433:1433
    volumes: 
            - mssql-volume:/var/opt/mssql
  redis:
    image: redis
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6378:6379"
    volumes:
       - ./data:/data
       - /tmp/redis:/tmp/redis
       - ./config/redis.conf:/usr/local/etc/redis/redis.conf
volumes:
    mssql-volume:
   